### ISSUE TITLE
MobileNet() - Use of unresolved identifier

### ISSUE THREAD

**Issue by RobRoyce** [NilStack/HelloVision#2]
The project will not compile and the MobileNet.mlmodel title is highlighted red. 

Error: /.../HelloVision/HelloVision/ViewController.swift:17:17: Use of unresolved identifier 'MobileNet'

**Comment by jsahoo** [comment]
@RobRoyce I fixed this by deleting MobileNet.mlmodel in the Project Navigator, downloading it separately (https://github.com/NilStack/HelloVision/blob/master/HelloVision/MobileNet.mlmodel), then dropping it into the Project Navigator. When you Run you might still see the Compiler Error but it will succeed

**Comment by RobRoyce** [comment]
@jsahoo this worked! Thanks for the help. -Rob

**Comment by yeldarby** [comment]
I had the same issue. I had to check the box next to `HelloVision` under `Target Membership` to get it to work.
![screen shot 2017-07-09 at 2 25 54 pm](https://user-images.githubusercontent.com/870796/27996919-90033d98-64b2-11e7-881b-9b04b5538f2e.png)

**Comment by yeldarby** [comment]
Just to note, it's because the path is pointing to your Desktop, not the included model.
![screen shot 2017-07-09 at 2 31 30 pm](https://user-images.githubusercontent.com/870796/27996961-57502258-64b3-11e7-80a4-0366f2e12fa5.png)

**Comment by senryxie** [comment]
Thanks guys.
